#
# Module manifest for module 'aitools'
#
# Generated by: Chrissy LeMaire
#
# Generated on: 4/7/2024
#
@{
    # Version number of this module.
    ModuleVersion     = '0.0.1'

    # ID used to uniquely identify this module
    GUID              = 'c90f5001-c492-4fbe-8ab3-f03599951bd0'

    # Author of this module
    Author            = 'Chrissy LeMaire'

    # Company or vendor of this module
    CompanyName       = 'Chrissy LeMaire'

    # Copyright statement for this module
    Copyright         = '2025 Chrissy LeMaire'

    # Description of the functionality provided by this module
    Description       = 'aitools'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @('PSOpenAI')

    PrivateData       = @{
        # PSData is module packaging and gallery metadata embedded in PrivateData
        # It's for rebuilding PowerShellGet (and PoshCode) NuGet-style packages
        # We had to do this because it's the only place we're allowed to extend the manifest
        # https://connect.microsoft.com/PowerShell/feedback/details/421837
        PSData = @{
            # The primary categorization of this module (from the TechNet Gallery tech tree).
            Category     = "AI"

            # Keyword tags to help users find this module via navigations and search.
            Tags         = @('ai', 'chatgpt', 'openai', 'claude', 'anthropic', 'aider', 'codex', 'coding')

            # The web address of an icon which can be used in galleries to represent this module
            IconUri      = ""

            # Indicates this is a pre-release/testing version of the module.
            IsPrerelease = 'False'
        }
    }
}