#
# Module manifest for module 'aitools'
#
# Generated by: Chrissy LeMaire
#
# Generated on: 4/7/2024
#
@{
    RootModule        = 'aitools.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.12'

    # ID used to uniquely identify this module
    GUID              = 'c90f5001-c492-4fbe-8ab3-f03599951bd0'

    # Author of this module
    Author            = 'Chrissy LeMaire'

    # Copyright statement for this module
    Copyright         = '2025 Chrissy LeMaire'

    # Description of the functionality provided by this module
    Description       = 'PowerShell wrapper for AI coding assistants. Batch process files using Claude Code, Aider, Gemini CLI, GitHub Copilot CLI, and Codex CLI with unified commands and pipeline support.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @(
        @{ ModuleName = 'PSFramework'; ModuleVersion = '1.7.249' },
        @{ ModuleName = 'Microsoft.PowerShell.ThreadJob'; ModuleVersion = '2.2.0' }
    )

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess  = @('aitools.format.ps1xml')

    # Public functions
    FunctionsToExport = @(
        'Clear-AIToolConfig',
        'Get-AITool',
        'Get-AIToolConfig',
        'Get-AITPrompt',
        'Install-AITool',
        'Initialize-AITool',
        'Invoke-AITool',
        'Remove-AIToolConfig',
        'Set-AIToolConfig',
        'Set-AIToolDefault',
        'Uninstall-AITool',
        'Update-AITool',
        'Update-PesterTest'
    )

    PrivateData       = @{
        # PSData is module packaging and gallery metadata embedded in PrivateData
        # It's for rebuilding PowerShellGet (and PoshCode) NuGet-style packages
        # We had to do this because it's the only place we're allowed to extend the manifest
        # https://connect.microsoft.com/PowerShell/feedback/details/421837
        PSData = @{
            # The primary categorization of this module (from the TechNet Gallery tech tree).
            Category     = "AI"

            # Keyword tags to help users find this module via navigations and search.
            Tags         = @('AI', 'CLI', 'Claude', 'Aider', 'Gemini', 'Copilot', 'Codex', 'Automation', 'CodeGeneration')

            # The web address of an icon which can be used in galleries to represent this module
            IconUri      = "https://raw.githubusercontent.com/potatoqualitee/aitools/main/logo.png"

            # The web address of the project site
            ProjectUri   = "https://github.com/potatoqualitee/aitools"

            # Indicates this is a pre-release/testing version of the module.
            IsPrerelease = 'False'
        }
    }
}